// This file imports and exports all images, making them available as modules
// Amenities SVGs
export const amenities = {
  air_condtion: require("./amenities/air_condtion.svg"),
  "air_condtion-white": require("./amenities/air_condtion-white.svg"),
  baggage: require("./amenities/baggage.svg"),
  "baggage-white": require("./amenities/baggage-white.svg"),
  charging_plug: require("./amenities/charging_plug.svg"),
  "charging_plug-white": require("./amenities/charging_plug-white.svg"),
  coffee: require("./amenities/coffee.svg"),
  cortina_divisoria: require("./amenities/cortina_divisoria.svg"),
  "divider-curtain": require("./amenities/divider-curtain.svg"),
  food_new_icon: require("./amenities/food_new_icon.svg"),
  "food_new_icon-white": require("./amenities/food_new_icon-white.svg"),
  frazda_amenity: require("./amenities/frazda_amenity.svg"),
  handicap: require("./amenities/handicap.svg"),
  "handicap-white": require("./amenities/handicap-white.svg"),
  "Icon_More-Amenities": require("./amenities/Icon_More-Amenities.svg"),
  "icon-app-cortina": require("./amenities/icon-app-cortina.svg"),
  mobile_ticket: require("./amenities/mobile_ticket.svg"),
  "mobile_ticket-white": require("./amenities/mobile_ticket-white.svg"),
  movie: require("./amenities/movie.svg"),
  "movie-white": require("./amenities/movie-white.svg"),
  music: require("./amenities/music.svg"),
  "music-white": require("./amenities/music-white.svg"),
  Restrooms: require("./amenities/Restrooms.svg"),
  "Restrooms-white": require("./amenities/Restrooms-white.svg"),
  snacks_new: require("./amenities/snacks_new.svg"),
  "snacks_new-white": require("./amenities/snacks_new-white.svg"),
  "whatsapp-charges-info-icon": require("./amenities/whatsapp-charges-info-icon.svg"),
  wifi: require("./amenities/wifi.svg"),
  "wifi-white": require("./amenities/wifi-white.svg"),
  // PNG
  "amenity-cortina": require("./amenities/amenity-cortina.png"),
};
